# Introduction to Numpy

In [2]:
# Numpy Arrays
import numpy as np

In [3]:
# Single array
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# Two dimensional arrays/matrix
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Similar to Range function in python
np.arange(0,10,2) # From [0,10) with 2 steps

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
# Similar to arange but instead splits the points up evenly
np.linspace(0,5,10) # Split up the range of 0 to 5 into 10 even pieces

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
# Make an Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Random one dimensional array
np.random.rand(5)

array([0.75025868, 0.35447872, 0.8028151 , 0.2091438 , 0.25430027])

In [13]:
# Random two dimensional array/matrix
np.random.rand(5,5)

array([[0.16078182, 0.89777726, 0.37232236, 0.00983744, 0.49066331],
       [0.35423412, 0.65702935, 0.96564152, 0.76709719, 0.83868598],
       [0.45617981, 0.30871566, 0.33979333, 0.51156284, 0.69784349],
       [0.70917175, 0.5284009 , 0.91695576, 0.77116506, 0.3176259 ],
       [0.02732956, 0.31699148, 0.66128025, 0.56040681, 0.98670806]])

In [14]:
# Return random samples from a gaussian/standard normal distribution centered around 0
np.random.randn(4,4)

array([[ 0.55105905, -0.75459831, -0.90511903,  1.71256552],
       [-1.01470266, -0.95869543,  1.41664639,  0.18134289],
       [-0.91367291,  1.70385002, -0.79182335,  0.63373406],
       [ 1.42109226, -0.39843303,  0.02145726, -0.13017764]])

In [15]:
# Random integer from range
np.random.randint(1,100) # 1 is inclusive but 100 is excluse, i.e., [1,100) in interval notation

20

In [16]:
np.random.randint(1,100,10)

array([35, 46, 37, 92, 96, 62, 62, 64, 98,  2])

In [17]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)
ranarr

array([20,  7, 23, 38, 43,  2, 11,  4, 14, 22])

In [19]:
# Reshape the data into a different matrix size and dimensions
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr.max() # Get max from array

43

In [21]:
ranarr.min() # Get min from array

2

In [22]:
ranarr.argmax() # returns the location of the max

4

In [23]:
ranarr.argmin() # returns the location of the min

5

In [24]:
arr.shape # Returns the shape of the array

(25,)

In [25]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.shape

(5, 5)

In [27]:
# What datatype is in the array?
arr.dtype

dtype('int64')

In [28]:
# another shortcut
from numpy.random import randint
randint(2,10)

9

# NumPy Indexing & Selection

In [30]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[8]

8

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:5] = 100 # Change multiple index
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
arr = np.arange(0,11)

In [36]:
# If we want to copy and not make a reference to the original array
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr_2d = np.arange(5,46,5)
arr_2d = arr_2d.reshape(3,3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
# We can index like this normally
arr_2d[2][1]

40

In [42]:
# Or this
arr_2d[2,1]

40

In [43]:
# Grab a subsection
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr = np.arange(0,11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [45]:
# conditional selection
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [46]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [50]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
arr / arr

/var/folders/vr/sdqsty_d49bg8cdvl7kw6vz80000gn/T/ipykernel_60483/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
1 / arr

/var/folders/vr/sdqsty_d49bg8cdvl7kw6vz80000gn/T/ipykernel_60483/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [53]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [55]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [56]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [57]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [58]:
np.log(arr)

/var/folders/vr/sdqsty_d49bg8cdvl7kw6vz80000gn/T/ipykernel_60483/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])