# Introduction to Numpy

In [2]:
# Numpy Arrays
import numpy as np

In [3]:
# Single array
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# Two dimensional arrays/matrix
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Similar to Range function in python
np.arange(0,10,2) # From [0,10) with 2 steps

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Similar to arange but instead splits the points up evenly
np.linspace(0,5,10) # Split up the range of 0 to 5 into 10 even pieces

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
# Make an Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Random one dimensional array
np.random.rand(5)

array([0.71882246, 0.41282453, 0.79591192, 0.29664318, 0.71861736])

In [18]:
# Random two dimensional array/matrix
np.random.rand(5,5)

array([[0.10590626, 0.61610937, 0.4583151 , 0.27166172, 0.91279434],
       [0.33582053, 0.57299134, 0.66829329, 0.85005984, 0.40762576],
       [0.42102302, 0.87317718, 0.60972188, 0.62838751, 0.78120522],
       [0.67685614, 0.91513348, 0.71666731, 0.74989478, 0.61849265],
       [0.05282098, 0.84452342, 0.07193179, 0.74227992, 0.81569242]])

In [22]:
# Return random samples from a gaussian/standard normal distribution centered around 0
np.random.randn(4,4)

array([[-0.90343133,  1.28681218, -0.84410842, -0.56302624],
       [-0.36872205,  0.11665206,  0.95170504,  0.2087042 ],
       [ 0.08602238, -0.85610688,  0.5799039 , -0.43906449],
       [-0.22504144,  0.36520393, -0.85634182,  1.75349326]])

In [23]:
# Random integer from range
np.random.randint(1,100) # 1 is inclusive but 100 is excluse, i.e., [1,100) in interval notation

52

In [24]:
np.random.randint(1,100,10)

array([49,  1,  5, 70, 65, 23, 88, 22, 12, 72])

In [25]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 2, 43, 48, 34, 16, 43,  8, 48, 35, 11])

In [28]:
# Reshape the data into a different matrix size and dimensions
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max() # Get max from array

48

In [31]:
ranarr.min() # Get min from array

2

In [32]:
ranarr.argmax() # returns the location of the max

2

In [33]:
ranarr.argmin() # returns the location of the min

0

In [34]:
arr.shape # Returns the shape of the array

(25,)

In [35]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [38]:
# What datatype is in the array?
arr.dtype

dtype('int64')

In [39]:
# another shortcut
from numpy.random import randint
randint(2,10)

4

# NumPy Indexing & Selection